version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}
